using System;
using System.CodeDom;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Xml;
using Colors.Core;

namespace Colors.Android
{
	public class ComponentColorsAndroidTask : BaseTask
	{
		protected override void GenerateForDirectory(string directory, Dictionary<string, string> keyValues)
		{
			//write colors.xml file
			XmlDocument document = new();
			document.AppendChild(document.CreateXmlDeclaration("1.0", "utf-8", null));
			XmlNode rootNode = document.CreateElement("resources");
			rootNode.AppendChild(document.CreateComment("This file was generated by ComponentColors task for Android"));
			document.AppendChild(rootNode);

			foreach (KeyValuePair<string, string> pair in keyValues)
			{
				XmlNode elementNode = document.CreateElement("color");
				elementNode.InnerText = pair.Value;

				XmlAttribute attributeName = document.CreateAttribute("name");
				attributeName.Value = pair.Key;
				elementNode.Attributes.Append(attributeName);

				rootNode.AppendChild(elementNode);
			}

			string filepath = Path.Combine(directory, "colors.xml");
			document.SaveIfDifferent(filepath);
			OutputResourceFilePath.Add(filepath);

			base.GenerateForDirectory(directory, keyValues);
		}

		protected override void GenerateForProject(List<string> keys)
		{
			GenerateColorService(keys);
			GenerateColors(keys);

			base.GenerateForProject(keys);
		}

		protected virtual void GenerateColorService(List<string> keys)
		{
			CodeCompileUnit codeUnit = new();

			// add namespace
			CodeNamespace codeNamespace = new(GenerationNamespace);
			codeUnit.Namespaces.Add(codeNamespace);

			codeNamespace.Imports.Add(new CodeNamespaceImport(DefaultNamespace));
			codeNamespace.Imports.Add(new CodeNamespaceImport("Android.Content"));
			codeNamespace.Imports.Add(new CodeNamespaceImport("Android.Graphics"));
			codeNamespace.Imports.Add(new CodeNamespaceImport("Android.OS"));

			// create class
			CodeTypeDeclaration classDeclaration = new(ColorConstants.IMPLEMENTATION_SERVICE_NAME)
			{
				IsClass = true,
				TypeAttributes = TypeAttributes.Public,
			};
			classDeclaration.BaseTypes.Add(ColorConstants.INTERFACE_SERVICE_NAME);
			codeNamespace.Types.Add(classDeclaration);

			//field
			CodeMemberField field = new("Context", ColorConstants.CONTEXT_FIELD_NAME)
			{
				Attributes = MemberAttributes.Private
			};
			classDeclaration.Members.Add(field);

			//constructor
			CodeConstructor constructor = new()
			{
				Attributes = MemberAttributes.Public
			};
			constructor.Parameters.Add(new CodeParameterDeclarationExpression("Context", ColorConstants.CONTEXT_PARAMETER_NAME));
			constructor.Statements.Add(new CodeAssignStatement(new CodeFieldReferenceExpression(new CodeThisReferenceExpression(), ColorConstants.CONTEXT_FIELD_NAME), new CodeVariableReferenceExpression(ColorConstants.CONTEXT_PARAMETER_NAME)));
			classDeclaration.Members.Add(constructor);

			//wrapped method
			CodeMemberMethod wrappedMethod = new()
			{
				Name = "GetWrappedColor",
				ReturnType = new CodeTypeReference(typeof(int)),
				Attributes = MemberAttributes.Private
			};
			wrappedMethod.Parameters.Add(new CodeParameterDeclarationExpression(typeof(int), "colorId"));
			classDeclaration.Members.Add(wrappedMethod);

			CodeFieldReferenceExpression contextReference = new(new CodeThisReferenceExpression(), ColorConstants.CONTEXT_FIELD_NAME);
			CodeMethodReferenceExpression getColorApi23 = new(contextReference, "GetColor");
			CodeFieldReferenceExpression resourcesReference = new(contextReference, "Resources");
			CodeMethodReferenceExpression getColor = new(resourcesReference, "GetColor");
			CodeVariableReferenceExpression paramRef = new("colorId");
			CodeMethodReturnStatement trueReturn = new(new CodeMethodInvokeExpression(getColorApi23, paramRef));
			CodeMethodReturnStatement falseReturn = new(new CodeMethodInvokeExpression(new CodeMethodInvokeExpression(getColor, paramRef), "ToArgb"));
			CodeTypeReferenceExpression buildRef = new("Build");
			CodePropertyReferenceExpression versionRef = new(buildRef, "VERSION");
			CodePropertyReferenceExpression sdkIntRef = new(versionRef, "SdkInt");
			CodeTypeReferenceExpression buildVersionRef = new("BuildVersionCodes");
			CodePropertyReferenceExpression mRef = new(buildVersionRef, "M");
			CodeBinaryOperatorExpression comparison = new(sdkIntRef, CodeBinaryOperatorType.GreaterThanOrEqual, mRef);
			CodeConditionStatement conditionalReturn = new(comparison, new CodeStatement[] { trueReturn }, new CodeStatement[] { falseReturn });
			wrappedMethod.Statements.Add(conditionalReturn);

			CodeMethodReferenceExpression wrappedMethodReference = new(new CodeThisReferenceExpression(), "GetWrappedColor");

			//methode
			CodeMemberMethod method = new()
			{
				Name = ColorConstants.SERVICE_METHOD_NAME,
				ReturnType = new CodeTypeReference(typeof(uint)),
				Attributes = MemberAttributes.Public | MemberAttributes.Final
			};
			method.Parameters.Add(new CodeParameterDeclarationExpression(ColorConstants.ENUM_NAME, "key"));
			classDeclaration.Members.Add(method);

			CodeVariableReferenceExpression methodParam = new("key");
			CodeTypeReferenceExpression androidColorId = new("Resource.Color");

			foreach (string key in keys)
			{
				CodeConditionStatement condition = new(
					new CodeBinaryOperatorExpression(
						methodParam,
						CodeBinaryOperatorType.IdentityEquality,
						new CodePropertyReferenceExpression(new CodeVariableReferenceExpression(ColorConstants.ENUM_NAME), key)
					),
					new CodeMethodReturnStatement(new CodeCastExpression(typeof(uint), new CodeMethodInvokeExpression(wrappedMethodReference, new CodePropertyReferenceExpression(androidColorId, key))))
				);

				method.Statements.Add(condition);
			}

			method.Statements.Add(new CodeThrowExceptionStatement(new CodeObjectCreateExpression(typeof(ArgumentOutOfRangeException))));

			codeUnit.WriteToFile(ColorConstants.IMPLEMENTATION_SERVICE_FILE_PATH, "This file was generated by ComponentColors task for Android");
			OutputCompileFilePath.Add(ColorConstants.IMPLEMENTATION_SERVICE_FILE_PATH);
		}

		protected virtual void GenerateColors(List<string> keys)
		{
			CodeCompileUnit codeUnit = new();

			// ajout namespace
			CodeNamespace codeNamespace = new(GenerationNamespace);
			codeUnit.Namespaces.Add(codeNamespace);

			codeNamespace.Imports.Add(new CodeNamespaceImport(DefaultNamespace));
			codeNamespace.Imports.Add(new CodeNamespaceImport("Android.Content"));
			codeNamespace.Imports.Add(new CodeNamespaceImport("Android.Graphics"));
			codeNamespace.Imports.Add(new CodeNamespaceImport("Android.OS"));

			// create class
			CodeTypeDeclaration classDeclaration = new(ColorConstants.COLORS_NAME)
			{
				IsClass = true,
				TypeAttributes = TypeAttributes.NestedAssembly | TypeAttributes.Sealed,
			};
			codeNamespace.Types.Add(classDeclaration);

			//field
			CodeMemberField field = new("Context", ColorConstants.CONTEXT_FIELD_NAME)
			{
				Attributes = MemberAttributes.Private | MemberAttributes.Static
			};
			classDeclaration.Members.Add(field);

			//initialize method
			CodeMemberMethod initializeMethod = new()
			{
				Name = "Initialize",
				Attributes = MemberAttributes.Public | MemberAttributes.Static
			};
			initializeMethod.Parameters.Add(new CodeParameterDeclarationExpression("Context", ColorConstants.CONTEXT_PARAMETER_NAME));
			initializeMethod.Statements.Add(new CodeAssignStatement(new CodeFieldReferenceExpression(new CodeTypeReferenceExpression(ColorConstants.COLORS_NAME), ColorConstants.CONTEXT_FIELD_NAME), new CodeVariableReferenceExpression(ColorConstants.CONTEXT_PARAMETER_NAME)));
			classDeclaration.Members.Add(initializeMethod);

			//constructor
			CodeConstructor constructor = new()
			{
				Attributes = MemberAttributes.Private
			};
			classDeclaration.Members.Add(constructor);

			//wrapped method
			CodeMemberMethod wrappedMethod = new()
			{
				Name = "GetWrappedColor",
				ReturnType = new CodeTypeReference("Color"),
				Attributes = MemberAttributes.Private | MemberAttributes.Static
			};

			wrappedMethod.Parameters.Add(new CodeParameterDeclarationExpression(typeof(int), "colorId"));
			classDeclaration.Members.Add(wrappedMethod);

			CodeFieldReferenceExpression contextReference = new(new CodeTypeReferenceExpression(ColorConstants.COLORS_NAME), ColorConstants.CONTEXT_FIELD_NAME);
			CodeFieldReferenceExpression resourcesReference = new(contextReference, "Resources");
			CodePropertyReferenceExpression themeRef = new(contextReference, "Theme");
			CodeMethodReferenceExpression getColorApi23 = new(resourcesReference, "GetColor");
			CodeMethodReferenceExpression getColor = new(resourcesReference, "GetColor");
			CodeVariableReferenceExpression paramRef = new("colorId");
			CodeMethodReturnStatement trueReturn = new(new CodeMethodInvokeExpression(getColorApi23, paramRef, themeRef));
			CodeMethodReturnStatement falseReturn = new(new CodeMethodInvokeExpression(getColor, paramRef));
			CodeTypeReferenceExpression buildRef = new("Build");
			CodePropertyReferenceExpression versionRef = new(buildRef, "VERSION");
			CodePropertyReferenceExpression sdkIntRef = new(versionRef, "SdkInt");
			CodeTypeReferenceExpression buildVersionRef = new("BuildVersionCodes");
			CodePropertyReferenceExpression mRef = new(buildVersionRef, "M");
			CodeBinaryOperatorExpression comparison = new(sdkIntRef, CodeBinaryOperatorType.GreaterThanOrEqual, mRef);
			CodeConditionStatement conditionnalReturn = new(comparison, new[] { trueReturn }, new[] { falseReturn });
			wrappedMethod.Statements.Add(conditionnalReturn);

			CodeMethodReferenceExpression wrappedMethodReference = new(new CodeTypeReferenceExpression(ColorConstants.COLORS_NAME), "GetWrappedColor");

			CodeTypeReferenceExpression androidColorId = new("Resource.Color");

			//properties
			foreach (string key in keys)
			{
				CodeMemberProperty property = new()
				{
					Name = key,
					Type = new CodeTypeReference("Color"),
					Attributes = MemberAttributes.Public | MemberAttributes.Static
				};

				property.GetStatements.Add(new CodeMethodReturnStatement(new CodeMethodInvokeExpression(wrappedMethodReference, new CodePropertyReferenceExpression(androidColorId, key))));

				classDeclaration.Members.Add(property);
			}

			codeUnit.WriteToFile(ColorConstants.COLORS_FILE_PATH, "This file was generated by ComponentColors task for Android");
			OutputCompileFilePath.Add(ColorConstants.COLORS_FILE_PATH);
		}
	}
}