<?xml version="1.0" encoding="utf-8"?>
<Project
        xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <UsingTask
            AssemblyFile="..\..\lib\net8.0-android34.0\Colors.Android.dll"
            TaskName="Colors.Android.ComponentColorsAndroidTask"/>
    <Target
            Name="ComponentColorsTask"
            BeforeTargets="BeforeBuild">
        <ComponentColorsAndroidTask
                InputFiles="@(ComponentColorFile)"
                OverrideFiles="@(ComponentColorOverrideFile)"
                DefaultNamespace="$(RootNamespace)">
            <Output
                    TaskParameter="OutputCompileFiles"
                    ItemName="StormOutputCompileFiles"/>
            <Output
                    TaskParameter="OutputResourceFiles"
                    ItemName="StormOutputResourceFiles"/>
        </ComponentColorsAndroidTask>
    </Target>
</Project>