version: 1.0.{build}
branches:
  only:
  - develop
  - master
skip_tags: true
image: Visual Studio 2017
before_build:
- cmd: >-
    nuget restore Storm.BuildTasks.sln
build:
  project: Storm.BuildTasks.sln
  parallel: true
  verbosity: minimal
test:
  assemblies:
    only:
      - tests\**\*.UnitTests.dll