using System;
using System.CodeDom;
using System.Collections.Generic;
using System.Globalization;
using System.Reflection;
using Colors.Core;

namespace Colors.iOS
{
	public class ComponentColorsIOSTask : BaseTask
	{
		protected override void GenerateForDirectory(string directory, Dictionary<string, string> keyValues)
		{
			GenerateColorService(keyValues);

			base.GenerateForDirectory(directory, keyValues);
		}

		protected override void GenerateForProject(List<string> keys)
		{
			GenerateColors(keys);

			base.GenerateForProject(keys);
		}

		protected virtual void GenerateColorService(Dictionary<string, string> keyValues)
		{
			CodeCompileUnit codeUnit = new();

			//add namespace
			CodeNamespace codeNamespace = new(GenerationNamespace);
			codeUnit.Namespaces.Add(codeNamespace);

			codeNamespace.Imports.Add(new CodeNamespaceImport("System"));

			//create class
			CodeTypeDeclaration classDeclaration = new(ColorConstants.IMPLEMENTATION_SERVICE_NAME)
			{
				IsClass = true,
				TypeAttributes = TypeAttributes.Public
			};
			classDeclaration.BaseTypes.Add(ColorConstants.INTERFACE_SERVICE_NAME);
			codeNamespace.Types.Add(classDeclaration);

			//methode
			CodeMemberMethod method = new()
			{
				Name = ColorConstants.SERVICE_METHOD_NAME,
				ReturnType = new CodeTypeReference(typeof(uint)),
				Attributes = MemberAttributes.Public
			};
			method.Parameters.Add(new CodeParameterDeclarationExpression(ColorConstants.ENUM_NAME, "key"));
			classDeclaration.Members.Add(method);

			CodeVariableReferenceExpression methodParam = new("key");

			foreach (KeyValuePair<string, string> pair in keyValues)
			{
				CodeConditionStatement condition = new(
					new CodeBinaryOperatorExpression(
						methodParam,
						CodeBinaryOperatorType.IdentityEquality,
						new CodePropertyReferenceExpression(new CodeVariableReferenceExpression(ColorConstants.ENUM_NAME), pair.Key)),
					new CodeMethodReturnStatement(new CodePrimitiveExpression(ProcessValue(pair.Value))));

				method.Statements.Add(condition);
			}

			method.Statements.Add(new CodeThrowExceptionStatement(new CodeObjectCreateExpression(typeof(ArgumentOutOfRangeException))));

			codeUnit.WriteToFile(ColorConstants.IMPLEMENTATION_SERVICE_FILE_PATH, "This file was generated by ComponentColors tasks for iOS");
			OutputCompileFilePath.Add(ColorConstants.IMPLEMENTATION_SERVICE_FILE_PATH);
		}

		private uint ProcessValue(string value)
		{
			if (value.StartsWith("#") && value.Length <= 7)
			{
				value = value.Insert(1, "FF");
			}

			if (uint.TryParse(value.Replace("#", string.Empty), NumberStyles.HexNumber, CultureInfo.InvariantCulture, out uint color))
			{
				return color;
			}
			else
			{
				Log.LogError($"Can't transform {value} in uint");
				return 0;
			}
		}

		protected virtual void GenerateColors(List<string> keys)
		{
			//TODO MAKE RETURN UICOLOR
			CodeCompileUnit codeUnit = new();
			// for class declaration
			CodeNamespace codeNamespace = new(GenerationNamespace);
			codeUnit.Namespaces.Add(codeNamespace);

			codeNamespace.Imports.Add(new CodeNamespaceImport("System"));

			// create class
			CodeTypeDeclaration classDeclaration = new(ColorConstants.COLORS_NAME)
			{
				IsClass = true,
				TypeAttributes = TypeAttributes.NestedAssembly | TypeAttributes.Sealed,
			};
			codeNamespace.Types.Add(classDeclaration);

			//private constructor
			CodeConstructor constructor = new()
			{
				Attributes = MemberAttributes.Private
			};
			classDeclaration.Members.Add(constructor);

			//field
			const string fieldName = "_service";
			CodeMemberField field = new($"Func<{ColorConstants.INTERFACE_SERVICE_NAME}>", fieldName)
			{
				Attributes = MemberAttributes.Private | MemberAttributes.Static
			};
			classDeclaration.Members.Add(field);

			//initialize method
			CodeMemberMethod initializeMethod = new()
			{
				Name = "Initialize",
				Attributes = MemberAttributes.Public | MemberAttributes.Static
			};
			initializeMethod.Parameters.Add(new CodeParameterDeclarationExpression($"Func<{ColorConstants.INTERFACE_SERVICE_NAME}>", "service"));
			initializeMethod.Statements.Add(new CodeAssignStatement(new CodeFieldReferenceExpression(new CodeTypeReferenceExpression(ColorConstants.COLORS_NAME), fieldName), new CodeVariableReferenceExpression("service")));
			classDeclaration.Members.Add(initializeMethod);

			CodeMethodInvokeExpression serviceReference = new(new CodeMethodReferenceExpression(new CodeFieldReferenceExpression(new CodeTypeReferenceExpression(ColorConstants.COLORS_NAME), fieldName), "Invoke"));
			CodeMethodReferenceExpression getColorMethod = new(serviceReference, ColorConstants.SERVICE_METHOD_NAME);
			foreach (string key in keys)
			{
				CodeMemberProperty property = new()
				{
					Name = key,
					Type = new CodeTypeReference(typeof(uint)),
					Attributes = MemberAttributes.Public | MemberAttributes.Static
				};

				property.GetStatements.Add(new CodeMethodReturnStatement(
					new CodeMethodInvokeExpression(getColorMethod, new CodePropertyReferenceExpression(new CodeVariableReferenceExpression(ColorConstants.ENUM_NAME), key))
				));
				classDeclaration.Members.Add(property);
			}

			codeUnit.WriteToFile(ColorConstants.COLORS_FILE_PATH, "This file was generated by ComponentColors task for iOS");
			OutputCompileFilePath.Add(ColorConstants.COLORS_FILE_PATH);
		}
	}
}