using System.CodeDom;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Colors.Core;
using Storm.BuildTasks.Common.Extensions;

namespace Colors.PCL
{
	public class ComponentColorsPCLTask : BaseTask
	{
		protected override void GenerateForProject(List<string> keys)
		{
			GenerateEnumColors(keys);

			GenerateColorService(keys);

			base.GenerateForProject(keys);
		}

		protected virtual void GenerateEnumColors(List<string> keys)
		{
			var codeUnit = new CodeCompileUnit();

			//ajout namespace
			var codeNamespace = new CodeNamespace(GenerationNamespace);
			codeUnit.Namespaces.Add(codeNamespace);

			//creation enum
			var enumDeclaration = new CodeTypeDeclaration(ColorConstants.ENUM_NAME)
			{
				IsEnum = true,
				TypeAttributes = TypeAttributes.Public
			};
			codeNamespace.Types.Add(enumDeclaration);

			//ajout des enums
			enumDeclaration.Members.AddRange(keys.Select(k => new CodeMemberField(ColorConstants.ENUM_FILE_PATH, k)).ToArray<CodeTypeMember>());

			codeUnit.WriteToFile(ColorConstants.ENUM_FILE_PATH, "This file was generated by ComponentColors task for PCL");
			OutputCompileFilePath.Add(ColorConstants.ENUM_FILE_PATH);
		}

		protected virtual void GenerateColorService(List<string> keys)
		{
			var codeUnit = new CodeCompileUnit();

			//ajout namespace
			var codeNamespace = new CodeNamespace(GenerationNamespace);
			codeUnit.Namespaces.Add(codeNamespace);

			//create interface
			var interfaceDeclaration = new CodeTypeDeclaration(ColorConstants.INTERFACE_SERVICE_NAME)
			{
				IsInterface = true,
				TypeAttributes = TypeAttributes.Interface | TypeAttributes.Public
			};
			codeNamespace.Types.Add(interfaceDeclaration);

			//ajout methode
			var method = new CodeMemberMethod
			{
				Name = ColorConstants.SERVICE_METHOD_NAME,
				ReturnType = new CodeTypeReference(typeof(uint))
			};
			method.Parameters.Add(new CodeParameterDeclarationExpression(ColorConstants.ENUM_NAME, "key"));
			interfaceDeclaration.Members.Add(method);

			codeUnit.WriteToFile(ColorConstants.INTERFACE_SERVICE_FILE_PATH, "This file was generated by ComponentColors task for PCL");
			OutputCompileFilePath.Add(ColorConstants.INTERFACE_SERVICE_FILE_PATH);
		}
	}
}